version: 2
updates:
  # Go modules (backend)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: [ @Satilianius ]
    labels: [ "backend" ]
    open-pull-requests-limit: 10
    groups:
      backend:
        patterns:
          - "*"

  # NPM (frontend in UI folder)
  - package-ecosystem: "npm"
    directory: "/UI"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: [ @Satilianius ]
    labels: [ "frontend" ]
    open-pull-requests-limit: 10
    groups:
      frontend:
        patterns:
          - "*"

  # Dockerfiles and docker-compose (root)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: [ @Satilianius ]
    labels: [ "backend", "docker" ]
    open-pull-requests-limit: 10
    groups:
      docker:
        patterns:
          - "*"

  # Dockerfiles in UI folder
  - package-ecosystem: "docker"
    directory: "/UI"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: [ @Satilianius ]
    labels: [ "frontend", "docker" ]
    open-pull-requests-limit: 10
    groups:
      docker:
        patterns:
          - "*"
