name: DailyTasks

services:
  backend:
    build: .
    container_name: DailyTasksBackend
    depends_on:
      - database
    environment:
      GO_ENV: dev
      DB_HOST: database
    ports:
      - "8080:8080"

  frontend:
    build: ./Frontend
    container_name: DailyTasksFrontend
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "19006:19006"
      - "8081:8081"

  database:
    image: postgres:17
    container_name: DailyTasksDB
    environment:
      POSTGRES_USER: Developer
      POSTGRES_PASSWORD: Development
      POSTGRES_DB: DailyTasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
