name: DailyTasks

services:
  app:
    build: .
    container_name: DailyTasksMain
    depends_on:
      - database
    environment:
      GO_ENV: dev
      DB_HOST: database
    ports:
      - "8080:8080"

  database:
    image: postgres:17
    container_name: DailyTasksDB
    environment:
      POSTGRES_USER: Developer
      POSTGRES_PASSWORD: Development
      POSTGRES_DB: DailyTasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
