name: DailyTasks

services:
  backend:
    build: .
    container_name: DailyTasksBackend
    depends_on:
      - database
    environment:
      GO_ENV: dev
      DB_HOST: database
    ports:
      - "8080:8080"

  database:
    image: postgres:17
    container_name: DailyTasksDB
    environment:
      POSTGRES_USER: Developer
      POSTGRES_PASSWORD: Development
      POSTGRES_DB: DailyTasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./UI
      dockerfile: Dockerfile
    container_name: DailyTasksFrontend
    depends_on:
      - backend
    ports:
      - "19000:19000" # Metro (native)
      - "19001:19001" # Dev tunnels
      - "19002:19002" # DevTools
      - "19006:19006" # Web
      - "8081:8081"   # Metro (used by web for assets/HMR)
    environment:
      # Let Expo DevTools bind on all interfaces
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # Helps the packager craft URLs browser/device can reach from the host
      # On Windows, host.docker.internal is often safer than localhost
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
      # Bind the web server to all interfaces
      - WEB_HOST=0.0.0.0

    volumes:
      # Mount source for live reload
      - ./UI:/app
      # Keep container node_modules isolated from the host
      - /app/node_modules

volumes:
  postgres_data:
