server:
  port: 8080
db:
  host: localhost
  port: 5432
  user: Developer
  password: Development
  name: DailyTasks
  SSLMode: prefer
  MaxOpenConnections: 25
  MaxIdleConnections: 25
  ConnMaxLifetimeMinutes: 5
